In [4]:
import torch
import numpy

In [ ]:
numarr = numpy.zeros(5)

In [ ]:
numarr

array([0., 0., 0., 0., 0.])

In [ ]:
torch_arr = torch.zeros(5)

In [ ]:
torch_arr.dtype

torch.float32

In [ ]:
numarr.dtype

dtype('float64')

In [ ]:
torch_arr = torch.ones(5,dtype=torch.float32)

In [ ]:
torch_arr

tensor([1., 1., 1., 1., 1.])

In [ ]:
torch_arr.dtype

torch.float64

In [ ]:
# Tensor addition / subtraction / multiplication same as numpy calculations
# All 2 D tensors are matrices
a = torch.rand(2,2)
b = torch.rand(2,2)

a+b
a/b

tensor([[0.1456, 1.4475],
        [5.5186, 0.8096]])

In [ ]:
c = torch.rand(3,3)
c

tensor([[0.4603, 0.5739, 0.7865],
        [0.4024, 0.9154, 0.3920],
        [0.4695, 0.4603, 0.4710]])

In [ ]:
# tensors will support math-matical calculations as normal number : below is one sample
c = torch.rand(2,3) * 2
c

tensor([[1.1063, 1.5476, 0.3739],
        [0.0518, 0.6170, 0.2943]])

In [ ]:
# with more than 3D are tensors. : which it looks like 2 different 2D matrices

In [ ]:
A = torch.ones([2,2,3])

B = torch.zeros_like(A)
B

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.ones_like(B)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
# Finally defining the tensors with the data itself.

In [ ]:
s_tensor = torch.tensor([[4,5,6],[3,4,5]])
s_tensor.shape

torch.Size([2, 3])

In [ ]:
m_tensor  = torch.tensor(((2,3,4),[4,5,6]))
m_tensor.shape

torch.Size([2, 3])

In [ ]:
b_tensor = m_tensor.detach().clone() # to copy the original tensor

In [ ]:
b_tensor

tensor([[2, 3, 4],
        [4, 5, 6]])

In [ ]:
b_tensor.to(torch.float64)

tensor([[2., 3., 4.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
# broadcasting   a 2D and 3D tensor

a = torch.rand(2,2)
a
b = torch.rand(1,2)
print(a)
print(b)

tensor([[0.8411, 0.7883],
        [0.1766, 0.2800]])
tensor([[0.0447, 0.2712]])


In [ ]:
a*b

tensor([[0.0376, 0.2138],
        [0.0079, 0.0759]])

In [ ]:
c = torch.ones(2,2)
d = torch.ones(1,2)

In [ ]:
print(c[1]*d[0])  # mostly i would say understand them as lists for now

tensor([1., 1.])


In [ ]:
c[0]
d[0][1]
c[0][1].shape
d[0][1].shape

torch.Size([])

In [ ]:
print(c*d)
e = c[0][1]*d
e

tensor([[1., 1.],
        [1., 1.]])


tensor([[1., 1.]])

In [ ]:
e

tensor([[1., 1.]])

In [ ]:
s1 = torch.ones(4,3,2)

In [ ]:
s2 = torch.ones(3,2)

In [ ]:
s1*s2

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
s3  = torch.ones(3,1)

In [ ]:
s1*s3

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [1]:
# unsqueeze and squeeze and effect of broad casting
# unsqueeze - helps in handling the batah based inputs to the nerual nets
# sequeeze - helps in removing the extra dimension in the vector size : probably can be used in the computations which requries the non batch inputs.

In [2]:
#unsqueeze helps in adding an extra dim such that it supports the calcualtions on broadcasting .

In [14]:
#ex:

a = torch.ones(2,2,2)
a

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [25]:
b = torch.ones(2,1)
b.unsqueeze(0)
# b

tensor([[[1.],
         [1.]]])

In [26]:
a*b

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])